# Generated by Django 6.0.7 on 2026-09-10 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompressionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('raw_prompt', models.TextField(help_text='Original verbose prompt')),
                ('sir_yaml', models.TextField(help_text='Compiled Semantic Intermediate Representation (YAML)')),
                ('target_model', models.CharField(default='gpt-4o', help_text='Target frontier model', max_length=64)),
                ('raw_token_count', models.IntegerField(default=0)),
                ('sir_token_count', models.IntegerField(default=0)),
                ('tokens_saved', models.IntegerField(default=0)),
                ('token_reduction_pct', models.FloatField(default=0.0)),
                ('fidelity_score', models.FloatField(default=1.0, help_text='Cosine similarity score (0.0 to 1.0)')),
                ('fidelity_passed', models.BooleanField(default=True, help_text='True if score >= 0.85')),
                ('compression_latency_ms', models.FloatField(default=0.0)),
                ('inference_latency_ms', models.FloatField(blank=True, null=True)),
                ('llm_response', models.TextField(blank=True, help_text='Output returned by frontier LLM', null=True)),
                ('compression_engine', models.CharField(default='gemini', help_text='Engine used (gemini, groq, ollama)', max_length=32)),
                ('status', models.CharField(choices=[('compressed', 'Compressed'), ('executed', 'Executed'), ('failed', 'Failed')], default='compressed', max_length=16)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_compres_created_321fa3_idx')],
            },
        ),
        migrations.CreateModel(
            name='CostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(max_length=64)),
                ('input_cost_per_1m', models.FloatField(default=0.0)),
                ('output_cost_per_1m', models.FloatField(default=0.0)),
                ('raw_input_cost_usd', models.FloatField(default=0.0)),
                ('sir_input_cost_usd', models.FloatField(default=0.0)),
                ('cost_saved_usd', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_log', to='api.compressionsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
