# Generated by Django 6.0.7 on 2026-09-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressionsession',
            name='compression_engine',
            field=models.CharField(default='gemini', help_text='Engine used (gemini, groq, ollama)', max_length=48),
        ),
        migrations.AlterField(
            model_name='compressionsession',
            name='status',
            field=models.CharField(choices=[('compressed', 'Compressed'), ('executed', 'Executed'), ('failed', 'Failed'), ('passthrough', 'Optimal (Pass-through)'), ('PASSTHROUGH_ALREADY_OPTIMAL', 'Pass-through (Already Optimal)'), ('PASSTHROUGH_NEGATIVE_SAVINGS', 'Pass-through (Negative Savings)')], default='compressed', max_length=40),
        ),
    ]
