# Generated by Django 6.0.7 on 2026-09-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_compressionsession_compression_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressionsession',
            name='client_ip',
            field=models.CharField(blank=True, help_text='Client IP for telemetry', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='compressionsession',
            name='compression_engine',
            field=models.CharField(default='gemini', help_text='Engine used (gemini, groq, ollama, proxy)', max_length=64),
        ),
        migrations.AlterField(
            model_name='compressionsession',
            name='status',
            field=models.CharField(choices=[('compressed', 'Compressed'), ('executed', 'Executed'), ('failed', 'Failed'), ('passthrough', 'Optimal (Pass-through)'), ('PASSTHROUGH_OPTIMAL', 'Pass-through (Optimal)'), ('PASSTHROUGH_ALREADY_OPTIMAL', 'Pass-through (Already Optimal)'), ('PASSTHROUGH_NEGATIVE_OVERHEAD', 'Pass-through (Negative Overhead)'), ('PASSTHROUGH_NEGATIVE_SAVINGS', 'Pass-through (Negative Savings)'), ('FALLBACK_FIDELITY_GUARD', 'Fallback (Fidelity Guard)'), ('FALLBACK', 'Fallback (General)')], default='compressed', max_length=64),
        ),
    ]
